//! 在mpsc_queue基础上更高级一点的包装。加入了线程空闲时等待与通信机制。

const std = @import("std");
const mpsc_queue = @import("mpsc_queue");
const Pollable = @import("Pollable.zig");

const runtime_safety = mpsc_queue.runtime_safety;

const MpscChannelError = error{
    MpscChannelAllProducersDone,
};

pub fn MpscChannel(MpscQueue: type) type {
    const MpscQueueHandle = if (MpscQueue.SourceGeneric == mpsc_queue.AnyMpscQueue) MpscQueue else if (MpscQueue.SourceGeneric == mpsc_queue.MpscQueue) *MpscQueue else @compileError("`MpscChannel` only accept a type generated by `mpsc_queue.MpscQueue()` or `mpsc_queue.AnyMpscQueue()`.");
    const T = MpscQueue.ItemType;
    const Sequence = MpscQueue.Sequence;
    const ProduceTicket = MpscQueue.ProduceTicket;
    const ProduceTickets = MpscQueue.ProduceTickets;
    const ConsumeTicket = MpscQueue.ConsumeTicket;
    const ProducerLocal = MpscQueue.ProducerLocal;
    const ConsumerLocal = MpscQueue.ConsumerLocal;
    return struct {
        mpsc_queue_ref: MpscQueueHandle,
        consumer_sync: ConsumerSyncBlock align(std.atomic.cache_line) = .{},
        producer_sync: ProducerSyncBlock align(std.atomic.cache_line) = .{},
        const ConsumerSyncBlock = struct {
            // 消费者进入等待状态时，它被设置为消费者的`consume_cursor_to_claim`
            // 这是考虑到`publishProduced`可以乱序生产，并不是所有生产都应该唤醒消费者，只有消费者确实正在等待的那个ticket的生产才应当唤醒消费者。
            // 当消费者从等待状态恢复，压根不需要重置此量，因为每个ticket只会被生产者生产一次，下一次生产者再生产，就不是这个ticket了。
            // 这个值初始化为Sequence的最大值。如果运行了50年，消费者从未阻塞，生产者撞到了Sequence最大值怎么办？
            // 答案是，让它撞，因为在此等坏情况下也不过是生产者发送了一个多余的signal，没有什么危害性。
            ticket_consumer_waiting_for: std.atomic.Value(Sequence) = .init(~@as(Sequence, 0)),
            cond: std.Thread.Condition = .{},
            mutex: std.Thread.Mutex = .{},
            done: bool = false,
        };
        const ProducerSyncBlock = struct {
            // `num_producer_waiting`是普通生产等待与强制批量生产等待之和。一旦存在强制批量生产，必须为broadcast而非signal。
            num_producer_waiting: std.atomic.Value(usize) = .init(0),
            // 批量生产者每当唤醒重新竞标此最小值。
            smallest_batch_size: usize = ~@as(usize, 0),
            vacancy_avail_cond: std.Thread.Condition = .{},
            vacancy_sufficient_cond: std.Thread.Condition = .{},
            mutex: std.Thread.Mutex = .{},
        };
        pub fn claimProduce(self: *@This(), cache: *ProducerLocal, on_wait: ?Pollable) struct { ProduceTicket, *T } {
            if (runtime_safety) {
                // 对于mpsc_channel而言，任何已申请而未发布的生产都有可能导致死锁。
                std.debug.assert(cache.unpublished_produce == 0);
            }
            return self.mpsc_queue_ref.claimProduce(cache) catch {
                if (on_wait) |cb| {
                    sw: switch (cb.operate(.run).?) {
                        .ready => {
                            return self.mpsc_queue_ref.claimProduce(cache) catch continue :sw cb.operate(.run).?;
                        },
                        .done => break :sw,
                    }
                }
                self.producer_sync.mutex.lock();
                defer self.producer_sync.mutex.unlock();
                _ = self.producer_sync.num_producer_waiting.fetchAdd(1, .acquire);
                defer _ = self.producer_sync.num_producer_waiting.fetchSub(1, .release);
                const ticket, const item_ref = self.mpsc_queue_ref.claimProduce(cache) catch blk: {
                    while (true) {
                        self.producer_sync.vacancy_avail_cond.wait(&self.producer_sync.mutex);
                        break :blk self.mpsc_queue_ref.claimProduce(cache) catch continue;
                    }
                };
                return .{ ticket, item_ref };
            };
        }
        pub fn claimProduceMultipleExact(self: *@This(), count: usize, cache: *ProducerLocal, on_wait: ?Pollable) ProduceTickets {
            if (runtime_safety) {
                // 对于mpsc_channel而言，任何已申请而未发布的生产都有可能导致死锁。
                std.debug.assert(cache.unpublished_produce == 0);
                // 请求超过capacity数量必然导致死锁。此外，请求数量为1也是浪费性能的，应该禁止。
                std.debug.assert(count <= self.mpsc_queue_ref.getCapacity() and count > 1);
            }
            return self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch {
                if (on_wait) |cb| {
                    sw: switch (cb.operate(.run).?) {
                        .ready => {
                            return self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch continue :sw cb.operate(.run).?;
                        },
                        .done => break :sw,
                    }
                }
                self.producer_sync.mutex.lock();
                defer self.producer_sync.mutex.unlock();
                _ = self.producer_sync.num_producer_waiting.fetchAdd(1, .acquire);
                defer _ = self.producer_sync.num_producer_waiting.fetchSub(1, .release);
                const tickets = self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch blk: {
                    while (true) {
                        if (count < self.producer_sync.smallest_batch_size) self.producer_sync.smallest_batch_size = count;
                        self.producer_sync.vacancy_sufficient_cond.wait(&self.producer_sync.mutex);
                        break :blk self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch continue;
                    }
                };
                return tickets;
            };
        }
        pub fn publishProducedUnsafe(self: *@This(), produce_ticket: ProduceTicket) void {
            self.mpsc_queue_ref.publishProducedUnsafe(produce_ticket);
            // [参见](https://github.com/ziglang/zig/pull/21585)
            // zig已经删除了`@fence`，因此，为了阻止实际的生产被重排到读取消费者等待票据之后，采用`fetchXor`逻辑，
            // 本质是`load(..., .release)`的Rmw操作版本，因为直接对`load`采用`.release`内存序是不被允许的。
            if (produce_ticket.v == self.consumer_sync.ticket_consumer_waiting_for.fetchXor(0, .release)) {
                self.consumer_sync.mutex.lock();
                // 在锁内没有再进行二次检查消费者等待票据，因为对应的防御措施在消费者端已经做了。
                // 由于没有二次检查，有概率产生错误的唤醒，但概率极低。
                self.consumer_sync.cond.signal();
                self.consumer_sync.mutex.unlock();
            }
        }
        pub fn claimConsume(self: *@This(), cache: *ConsumerLocal, on_wait: ?Pollable) !struct { ConsumeTicket, *T } {
            if (runtime_safety) {
                // 阻止过度申请consume行为导致死锁。
                std.debug.assert(cache.consume_cursor_to_claim -% cache.consume_cursor_to_release < self.mpsc_queue_ref.getCapacity());
            }
            return self.mpsc_queue_ref.claimConsume(cache) catch {
                if (on_wait) |cb| {
                    sw: switch (cb.operate(.run).?) {
                        .ready => {
                            return self.mpsc_queue_ref.claimConsume(cache) catch continue :sw cb.operate(.run).?;
                        },
                        .done => break :sw,
                    }
                }
                self.consumer_sync.mutex.lock();
                defer self.consumer_sync.mutex.unlock();
                // [参见](https://github.com/ziglang/zig/pull/21585)
                // zig已经删除了`@fence`，因此，为了阻止二次确认被被重排到设置消费者等待票据之前，采用`swap`逻辑，
                // 本质是`store(..., .acquire)`的Rmw操作版本，因为直接对`store`采用`.acquire`内存序是不被允许的。
                _ = self.consumer_sync.ticket_consumer_waiting_for.swap(cache.consume_cursor_to_claim, .acquire);
                // 确保不会错过唤醒。
                // 例如，如果在上面的`ticket_consumer_waiting_for`设置前，刚好生产者生产完毕同时进行了`ticket_consumer_waiting_for`校验。
                // 那么，此时如果直接进行等待，将会错过唤醒机会，永久地睡过去。再进行一次claimConsume进行检查才是安全的。
                // 此处的检查可能导致生产端发送一次冗余的信号，但没什么危害。
                const ticket, const item_ref = self.mpsc_queue_ref.claimConsume(cache) catch blk: {
                    // 由于存在虚假唤醒的可能（无可避免的50年一遇虚假信号，以及生产端自身未做二次校验带来的虚假唤醒可能），此次需要用`while`保证。
                    while (!self.consumer_sync.done) {
                        self.consumer_sync.cond.wait(&self.consumer_sync.mutex);
                        break :blk self.mpsc_queue_ref.claimConsume(cache) catch continue;
                    } else return error.MpscChannelAllProducersDone;
                };
                return .{ ticket, item_ref };
            };
        }
        pub fn releaseConsumedUnsafe(self: *@This(), consume_ticket: ConsumeTicket) void {
            self.mpsc_queue_ref.releaseConsumedUnsafe(consume_ticket);
            // [参见](https://github.com/ziglang/zig/pull/21585)
            // zig已经删除了`@fence`，因此，为了阻止实际的生产被重排到读取消费者等待票据之后，采用`fetchXor`逻辑，
            // 本质是`load(..., .release)`的Rmw操作版本，因为直接对`load`采用`.release`内存序是不被允许的。
            if (self.producer_sync.num_producer_waiting.fetchXor(0, .release) != 0) {
                self.producer_sync.mutex.lock();
                defer self.producer_sync.mutex.unlock();
                // 总是在非批量生产的等待队列发送一个信号。
                // 我们的mpsc channel鼓励使用仅单次生产而非强制批量生产，因此不会为判定是否存在单次生产进行更多状态保存与比较。
                self.producer_sync.vacancy_avail_cond.signal();
                if (self.producer_sync.smallest_batch_size != ~@as(usize, 0)) {
                    // 如果存在批量生产，且当前的空闲空间已经允许批量生产的最小值，对批量生产队列广播唤醒，然后重新竞标批量最小值。
                    if (self.producer_sync.smallest_batch_size <= self.mpsc_queue_ref.probeProduceVacancyForConsumer(consume_ticket.v +% 1)) {
                        self.producer_sync.vacancy_sufficient_cond.broadcast();
                        self.producer_sync.smallest_batch_size = ~@as(usize, 0);
                    }
                }
            }
        }
        pub fn notifyConsumerDone(self: *@This()) void {
            self.consumer_sync.mutex.lock();
            defer self.consumer_sync.mutex.unlock();
            self.consumer_sync.done = true;
            self.consumer_sync.cond.signal();
        }
    };
}

test MpscChannel {
    const BigStruct = struct {
        data: [80]u8,
    };
    const Queue = mpsc_queue.AnyMpscQueue(BigStruct, null);
    const Channel = MpscChannel(Queue);
    const Producer = struct {
        fn task(channel: *Channel, id: u8) void {
            var cache = channel.mpsc_queue_ref.initProducerLocal();
            if (id % 2 == 0) {
                for (0..100) |_| {
                    const ticket, const item_ref = channel.claimProduce(&cache, null);
                    defer channel.publishProducedUnsafe(ticket);
                    item_ref.* = .{ .data = @splat(id) };
                }
            } else {
                for (0..4) |_| {
                    var tickets = channel.claimProduceMultipleExact(25, &cache, null);
                    while (channel.mpsc_queue_ref.nextProduceTicket(&tickets)) |lease| {
                        const ticket, const item_ref = lease;
                        defer channel.publishProducedUnsafe(ticket);
                        item_ref.* = .{ .data = @splat(id) };
                    }
                }
            }
        }
    };
    const Consumer = struct {
        fn task(channel: *Channel) void {
            var consumer_cache = channel.mpsc_queue_ref.initConsumerLocal();
            var statistic: [8]usize = @splat(0);
            while (channel.claimConsume(&consumer_cache, null)) |lease| {
                const ticket, const item_ref = lease;
                defer channel.releaseConsumedUnsafe(ticket);
                const verify = struct {
                    const possible_product: [8][80]u8 = .{
                        @splat(0),
                        @splat(1),
                        @splat(2),
                        @splat(3),
                        @splat(4),
                        @splat(5),
                        @splat(6),
                        @splat(7),
                    };
                    fn check(to_check: *[80]u8) ?usize {
                        for (possible_product, 0..8) |expect, id| {
                            if (std.mem.eql(u8, &expect, to_check)) return id;
                        }
                        return null;
                    }
                };
                const id = verify.check(&item_ref.data);
                std.testing.expect(id != null) catch unreachable;
                statistic[id.?] += 1;
            } else |_| {}
            std.testing.expectEqual(statistic, @as([8]usize, @splat(100))) catch unreachable;
        }
    };
    const queue = try Queue.init(std.testing.allocator, 5);
    defer queue.deinit(std.testing.allocator);
    var channel: Channel = .{ .mpsc_queue_ref = queue };
    var consumer = try std.Thread.spawn(.{ .allocator = std.testing.allocator }, Consumer.task, .{&channel});
    var producers_pool: std.Thread.Pool = undefined;
    try producers_pool.init(.{ .allocator = std.testing.allocator });
    defer producers_pool.deinit();
    var wait_group: std.Thread.WaitGroup = .{};
    for (0..8) |i| {
        const id: u8 = @intCast(i);
        producers_pool.spawnWg(&wait_group, Producer.task, .{ &channel, id });
    }
    wait_group.wait();
    channel.notifyConsumerDone();
    consumer.join();
}
