//! 在mpsc_queue基础上更高级一点的包装。加入了线程空闲时等待与通信机制。

const std = @import("std");
const mpsc_queue = @import("mpsc_queue");
const Pollable = @import("Pollable.zig");

const runtime_safety = mpsc_queue.runtime_safety;

pub fn MpscChannel(MpscQueue: type) type {
    const MpscQueueHandle = if (MpscQueue.SourceGeneric == mpsc_queue.AnyMpscQueue) MpscQueue else if (MpscQueue.SourceGeneric == mpsc_queue.MpscQueue) *MpscQueue else @compileError("`MpscChannel` only accept a type generated by `mpsc_queue.MpscQueue()` or `mpsc_queue.AnyMpscQueue()`.");
    const T = MpscQueue.ItemType;
    const Sequence = MpscQueue.Sequence;
    const ProduceTicket = MpscQueue.ProduceTicket;
    const ConsumeTicket = MpscQueue.ConsumeTicket;
    const ProducerLocal = MpscQueue.ProducerLocal;
    const ConsumerLocal = MpscQueue.ConsumerLocal;
    return struct {
        mpsc_queue_ref: MpscQueueHandle,
        consumer_sync: ConsumerSyncBlock align(std.atomic.cache_line) = .{},
        producer_sync: ProducerSyncBlock align(std.atomic.cache_line) = .{},
        const ConsumerSyncBlock = struct {
            // 消费者进入等待状态时，它被设置为消费者的`consume_cursor_to_claim`
            // 这是考虑到`publishProduced`可以乱序生产，并不是所有生产都应该唤醒消费者，只有消费者确实正在等待的那个ticket的生产才应当唤醒消费者。
            // 当消费者从等待状态恢复，压根不需要重置此量，因为每个ticket只会被生产者生产一次，下一次生产者再生产，就不是这个ticket了。
            // 这个值初始化为Sequence的最大值。如果运行了50年，消费者从未阻塞，生产者撞到了Sequence最大值怎么办？
            // 答案是，让它撞，因为在此等坏情况下也不过是生产者发送了一个多余的signal，没有什么危害性。
            ticket_consumer_waiting_for: std.atomic.Value(Sequence) = .init(~@as(Sequence, 0)),
            product_avail_cond: std.Thread.Condition = .{},
            mutex: std.Thread.Mutex = .{},
        };
        const ProducerSyncBlock = struct {
            // `num_producer_waiting`是普通生产等待与强制批量生产等待之和。一旦存在强制批量生产，必须为broadcast而非signal。
            num_producer_waiting: std.atomic.Value(usize) = .init(0),
            // 用于标识当前是否有批量生产。
            num_batch_producer_waiting: usize = 0,
            // 批量生产者每当唤醒重新竞标此最小值。不能可靠地表达是否存在批量生产，必须依赖`num_batch_producer_waiting`。
            smallest_batch_size: usize = ~@as(usize, 0),
            vacancy_avail_cond: std.Thread.Condition = .{},
            vacancy_sufficient_cond: std.Thread.Condition = .{},
            mutex: std.Thread.Mutex = .{},
        };
        pub fn claimProduce(self: *@This(), cache: *ProducerLocal, on_wait: ?Pollable) struct { ProduceTicket, *T } {
            if (runtime_safety) {
                // 对于mpsc_channel而言，任何已申请而未发布的生产都有可能导致死锁。
                std.debug.assert(cache.unpublished_produce == 0);
            }
            return self.mpsc_queue_ref.claimProduce(cache) catch {
                if (on_wait) |cb| {
                    sw: switch (cb.operate(.run).?) {
                        .ready => {
                            return self.mpsc_queue_ref.claimProduce(cache) catch continue :sw cb.operate(.run).?;
                        },
                        .done => break :sw,
                    }
                }
                self.producer_sync.mutex.lock();
                _ = self.producer_sync.num_producer_waiting.fetchAdd(1, .acquire);
                const ticket, const item_ref = self.mpsc_queue_ref.claimProduce(cache) catch blk: {
                    while (true) {
                        self.producer_sync.vacancy_avail_cond.wait(&self.producer_sync.mutex);
                        break :blk self.mpsc_queue_ref.claimProduce(cache) catch continue;
                    }
                };
                _ = self.producer_sync.num_producer_waiting.fetchSub(1, .release);
                self.producer_sync.mutex.unlock();
                return .{ ticket, item_ref };
            };
        }
        pub fn claimProduceMultipleExact(self: *@This(), count: usize, cache: *ProducerLocal, on_wait: ?Pollable) mpsc_queue.Tickets(Sequence) {
            if (runtime_safety) {
                // 对于mpsc_channel而言，任何已申请而未发布的生产都有可能导致死锁。
                std.debug.assert(cache.unpublished_produce == 0);
                // 请求超过capacity数量必然导致死锁。此外，请求数量为1也是浪费性能的，应该禁止。
                std.debug.assert(count <= self.mpsc_queue_ref.getCapacity() and count > 1);
            }
            return self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch {
                if (on_wait) |cb| {
                    sw: switch (cb.operate(.run).?) {
                        .ready => {
                            return self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch continue :sw cb.operate(.run).?;
                        },
                        .done => break :sw,
                    }
                }
                self.producer_sync.mutex.lock();
                _ = self.producer_sync.num_producer_waiting.fetchAdd(1, .acquire);
                const ticket, const item_ref = self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch blk: {
                    self.producer_sync.num_batch_producer_waiting += 1;
                    while (true) {
                        if (count < self.producer_sync.smallest_batch_size) self.producer_sync.smallest_batch_size = count;
                        self.producer_sync.vacancy_sufficient_cond.wait(&self.producer_sync.mutex);
                        break :blk self.mpsc_queue_ref.claimProduceMultipleExact(count, cache) catch continue;
                    }
                    self.producer_sync.num_batch_producer_waiting -= 1;
                };
                _ = self.producer_sync.num_producer_waiting.fetchSub(1, .release);
                self.producer_sync.mutex.unlock();
                return .{ ticket, item_ref };
            };
        }
        pub fn publishProducedUnsafe(self: *@This(), produce_ticket: ProduceTicket) void {
            self.mpsc_queue_ref.publishProducedUnsafe(produce_ticket);
            // [参见](https://github.com/ziglang/zig/pull/21585)
            // zig已经删除了`@fence`，因此，为了阻止实际的生产被重排到读取消费者等待票据之后，采用`fetchXor`逻辑，
            // 本质是`load(..., .release)`的Rmw操作版本，因为直接对`load`采用`.release`内存序是不被允许的。
            if (produce_ticket.v == self.consumer_sync.ticket_consumer_waiting_for.fetchXor(0, .release)) {
                self.consumer_sync.mutex.lock();
                // 在锁内没有再进行二次检查消费者等待票据，因为对应的防御措施在消费者端已经做了。
                // 由于没有二次检查，有概率产生错误的唤醒，但概率极低。
                self.consumer_sync.product_avail_cond.signal();
                self.consumer_sync.mutex.unlock();
            }
        }
        pub fn claimConsume(self: *@This(), cache: *ConsumerLocal, on_wait: ?Pollable) struct { ConsumeTicket, *T } {
            if (runtime_safety) {
                // 阻止过度申请consume行为导致死锁。
                std.debug.assert(cache.consume_cursor_to_claim -% cache.consume_cursor_to_release < self.mpsc_queue_ref.getCapacity());
            }
            return self.mpsc_queue_ref.claimConsume(cache) catch {
                if (on_wait) |cb| {
                    sw: switch (cb.operate(.run).?) {
                        .ready => {
                            return self.mpsc_queue_ref.claimConsume(cache) catch continue :sw cb.operate(.run).?;
                        },
                        .done => break :sw,
                    }
                }
                self.consumer_sync.mutex.lock();
                // [参见](https://github.com/ziglang/zig/pull/21585)
                // zig已经删除了`@fence`，因此，为了阻止二次确认被被重排到设置消费者等待票据之前，采用`swap`逻辑，
                // 本质是`store(..., .acquire)`的Rmw操作版本，因为直接对`store`采用`.acquire`内存序是不被允许的。
                _ = self.consumer_sync.ticket_consumer_waiting_for.swap(cache.consume_cursor_to_claim, .acquire);
                // 确保不会错过唤醒。
                // 例如，如果在上面的`ticket_consumer_waiting_for`设置前，刚好生产者生产完毕同时进行了`ticket_consumer_waiting_for`校验。
                // 那么，此时如果直接进行等待，将会错过唤醒机会，永久地睡过去。再进行一次claimConsume进行检查才是安全的。
                // 此处的检查可能导致生产端发送一次冗余的信号，但没什么危害。
                const ticket, const item_ref = self.mpsc_queue_ref.claimConsume(cache) catch blk: {
                    // 由于存在虚假唤醒的可能（无可避免的50年一遇虚假信号，以及生产端自身未做二次校验带来的虚假唤醒可能），此次需要用`while`保证。
                    while (true) {
                        self.consumer_sync.product_avail_cond.wait(&self.consumer_sync.mutex);
                        break :blk self.mpsc_queue_ref.claimConsume(cache) catch continue;
                    }
                };
                self.consumer_sync.mutex.unlock();
                return .{ ticket, item_ref };
            };
        }
        pub fn releaseConsumedUnsafe(self: *@This(), consume_ticket: ConsumeTicket) void {
            self.mpsc_queue_ref.releaseConsumedUnsafe(consume_ticket);
            // [参见](https://github.com/ziglang/zig/pull/21585)
            // zig已经删除了`@fence`，因此，为了阻止实际的生产被重排到读取消费者等待票据之后，采用`fetchXor`逻辑，
            // 本质是`load(..., .release)`的Rmw操作版本，因为直接对`load`采用`.release`内存序是不被允许的。
            if (self.producer_sync.num_producer_waiting.fetchXor(0, .release) != 0) {
                self.producer_sync.mutex.lock();
                // XXX: 当前的唤醒策略的一个逻辑不一致之处：
                // 假如存在批量生产请求，它看似采用“最小唤醒策略”，只要满足最小批量生产的数量，就会进行广播唤醒。
                // 但是，案例“非批量的单个生产”才是最小的，但当前实现不会考虑“只要存在单个生产就会广播”。
                // 简单地说：当前的实现完全割裂了单个生产和多个生产，这保证了对于单个生产，完全不考虑可能有批量生产的情况。
                // 而存在批量生产的唤醒逻辑和单个生产不互通。
                if (self.producer_sync.num_batch_producer_waiting == 0) {
                    self.producer_sync.vacancy_avail_cond.signal();
                } else {
                    const vacancy = self.mpsc_queue_ref.probeProduceVacancyForConsumer(consume_ticket.v +% 1);
                    if (self.producer_sync.smallest_batch_size <= vacancy) {
                        // 对于符合批处理最小广播条件的情况，一定要同时对非批处理的生产进行广播。
                        // 让我们考虑这么一种极端情况：当消费者发现一个批处理生产满足条件以后，如果仅仅对批处理生产进行广播。
                        // 然而，消费者接下来抢在各批处理接收到广播之前，再次迅速消费多次，持续持有本锁。
                        // 由于其他生产者没有来得及重置`smallest_batch_size`，导致接下来的所有信号成功竞争得到锁前插入的连续消费都不会发送任何信号。
                        // 例如：当前有一个批量生产4，以及3个单次生产在等待状态。消费者抢在所有等待中的生产者接收到信号前连续消费了4次。
                        // 这将导致后续几次消费不会产生任何信号，进而3个单次生产本应接收信号却错过了。
                        // 为了避免此种情况发生，在广播批处理生产时，也必须为单次生产发送广播。
                        self.producer_sync.vacancy_avail_cond.broadcast();
                        self.producer_sync.vacancy_sufficient_cond.broadcast();
                        self.producer_sync.smallest_batch_size = ~@as(usize, 0);
                    }
                }
                self.producer_sync.mutex.unlock();
            }
        }
    };
}

test MpscChannel {
    const BigStruct = struct {
        data: [80]u8,
    };
    const Queue = mpsc_queue.AnyMpscQueue(BigStruct, null);
    const Channel = MpscChannel(Queue);
    const Producer = struct {
        fn task(channel: *Channel, id: u8) void {
            var cache = channel.mpsc_queue_ref.initProducerLocal();
            for (0..100) |_| {
                const ticket, const item_ref = channel.claimProduce(&cache, null);
                defer channel.publishProducedUnsafe(ticket);
                item_ref.* = .{ .data = @splat(id) };
            }
        }
    };
    var producers_pool: std.Thread.Pool = undefined;
    try producers_pool.init(.{ .allocator = std.testing.allocator });
    defer producers_pool.deinit();
    const queue = try Queue.init(std.testing.allocator, 5);
    defer queue.deinit(std.testing.allocator);
    var channel: Channel = .{ .mpsc_queue_ref = queue };
    var wait_group: std.Thread.WaitGroup = .{};
    for (0..8) |i| {
        const id: u8 = @intCast(i);
        producers_pool.spawnWg(&wait_group, Producer.task, .{ &channel, id });
    }
    {
        var consumer_cache = channel.mpsc_queue_ref.initConsumerLocal();
        var statistic: [8]usize = @splat(0);
        for (0..800) |_| {
            const ticket, const item_ref = channel.claimConsume(&consumer_cache, null);
            defer channel.releaseConsumedUnsafe(ticket);
            const verify = struct {
                const possible_product: [8][80]u8 = .{
                    @as([80]u8, @splat(0)),
                    @as([80]u8, @splat(1)),
                    @as([80]u8, @splat(2)),
                    @as([80]u8, @splat(3)),
                    @as([80]u8, @splat(4)),
                    @as([80]u8, @splat(5)),
                    @as([80]u8, @splat(6)),
                    @as([80]u8, @splat(7)),
                };
                fn check(to_check: *[80]u8) ?usize {
                    for (possible_product, 0..8) |expect, id| {
                        if (std.mem.eql(u8, &expect, to_check)) return id;
                    }
                    return null;
                }
            };
            const id = verify.check(&item_ref.data);
            try std.testing.expect(id != null);
            statistic[id.?] += 1;
        }
        try std.testing.expectEqual(statistic, @as([8]usize, @splat(100)));
    }
    wait_group.wait();
}
